server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/upload?characterEncoding=utf-8
    username: root
    password: fordearme2018
  redis:
    host: 127.0.0.1
    port: 6379
    password: fordearme2018
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 2000ms
  # 定义字符编码
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true



# 定义日志
logging:
  config: logback.xml
  level:
    com.chengnanhuakai.upload.mapper: trace



# 七牛云配置
