server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.99.77:3306/upload?characterEncoding=utf-8
    username: aaryn
    password: superman713
  redis:
    host: 111.231.99.77
    port: 6379
    password: cnh1k2jJhz!
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 2000ms



logging:
  config: logback.xml
  level:
    com.chengnanhuakai.upload.mapper: trace

# 七牛云配置
qiniu:
  accessKey: 62UNf6EeRYaQ8wUdc5CWm3II4zvaxnb7tYTNEKCJ
  secretKey: T31i2JI2DytG4P-6F4g3CwN_WcVLnnODuXgYLeFn
  bucket: chengnan
