server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/upload?characterEncoding=utf-8
    username: root
    password: fordearme2018
  redis:
    host: 127.0.0.1
    port: 6379
    password: fordearme2018
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 2000ms
  mvc:
    view:
      prefix: /templates
      suffix: .html


logging:
  config: logback.xml
  level:
    com.chengnanhuakai.upload.mapper: trace

# 七牛云配置
qiniu:
  accessKey: sfasf
  secretKey: asdasd
  bucket: chengnan

pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016091600526650
    privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYAuKKRIWNCUwScswGzzV9z654ZIJ85DxDpNuHnfCWgRYsKvO/NbgqdZQi/LqT6kZcUGrdA6psnzVdriSadz+VMn7gNdzinynUrPj0cL/0u9a/IIULVIleTVuwrtpCCsdpmML9Hrr9L4+KnNo8/2ET8jP9CGtOHKpmz677Xm1bRL9PZf0WmtRkiGCjZFhKZL232zQCzNE06PEMTY01N/deVqd3TKgAtvTF3Ro+2tfO+jfSkdHDZLwq+qv5zrpu1NENJsKYeCF9hCGRTiTickeuOucHA2PNwVFIjjLQfXidanxyTrik6hjlpXwPZdoeqlgfZTvU+MLw/V7mwnf27AArAgMBAAECggEAfOMp4bUoD9ZKlIGSFCoa5XFCAxF4j0koJd8EqWfeKJiHceQb+8UTuHZ/LTt7wlhgVCmRkmEXnEQ1IPEYi3tbVqV0zZoTDnD7egpeQt17J4NHjCEYjVV3wm1F3mPZVxbp/FyQHksoDykLAjOZrTGXPT7o7YMEPdmZOfx443YR3D/byeI4zPKYti0Fa1asYimQBe+2JIHRKpdgifFX3k66syTC5OnEw0uSsD617rvf6PnPM0QdAOodRUEg/JUUzzKUGbUtSfEOX2OsJlaI7HlasrCr4YhRlhwpEdIr7RJOaYlVhraQtoUSuS168CBAbPyPVjQqkhM9RH9yyVdIo89PkQKBgQDIdm5UTe5nvUW6ls3MvNdTd6KGffGaLTV8vHwMV1ev+ZcqvdxeLgkI7UYmYPdWVFEeqeQ8LqrZxSWcEn+sqKkWLADG6CEHpd37R57Y2HjAA5hGqnJLYrbulhqhM8ZsDBy3BRfCoKLuul0orExKsZPcaQeZErKHNyIl0GJSfZLMYwKBgQDCIBm0GBxkKuRILs+cWMqQBzwFF52aJEwPm803Ne2Cw69YZDvSw3yoyKaEqP692nKD2diMzcyhd7s3FSDSxMVpDVTKt1xwVw1XDisqnA15eozz0A8XPKk3NQjOZyJ+xKnu8XjS7rBDYZ8Ykf0LZT9j1giVG31pxASoXT301tGTmQKBgQDGGrQBwFpATv4f3XRYRq8NH4eQHdqroM3hDWwRzicsEx5e8O5cbGYlWkcfGmiT+hOImCCjkQLq3zfBu05NVQh0jtvdtf0eT77F2wuSBKugJm1QOJVnBpD9y31ZnY8TrAycmf3XK2SZQ7dYwJ1Mm50iDvGhRqcDlWq7r+na15pBPQKBgHFCAT0NhCL800s55G63bxcw4VenO5Ae9TF2GPjJQdU1Dixn7m89FpHy3xQu9NEXjhBXHPypZWYfUN8GOKw/mV19JadP62Kvp1zPK2gku8fQNERbczJ/dcp76rNhgMKtQufhgjiugbAOWKAhLJ1laOJ6kW9NJpJ6hq0kGW2rl4KhAoGBALCet9ir/2TpTNO26emWtvA/2HtDpFByxhGRekoxuFzJQAiNXkZD+lReUuR8dJEe9flA9r/XOyAAS0lBMX3iXk8uFY8ACQKrUJOPaXS5C5CNnFTpK5SeojyVphu7HnlbN4jEvl3C2rRaQoE3fCbTG/I3gNRjHW262tZMykJsb1uX
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1nK+cmDi+C98e71gOCWxYhh1AlBfeaN96lcAEbUP/WKNEkgUE1Fi0O8rVuHTuBmXHqTtM9OH1E/tW5h6fJSxZiydOLdd/qYajn8/ibYzww+Io+BaJmHEL0YhNb/FiIzn2a492wTtxC+UReF4AcfK1f6jm58CKyOiOfvgu7A4IwBx6ee0TstX9XSJRsHA3qFnFtcX3zZjg2z/SH+kOt8QUzqh62Rff8KItipZ2c5Da9lBVwzQD62LCiVgkzDofHkaJScreFbIKnNAHA8GSP80MeUF2ioSzxwxHq1P/JNLjxHo9en4uM4fzOaUExLk8cCbXojeU3BkbL3zcN8n69w2jQIDAQAB
    returnUrl: http://www.fordearme.com/pay/alipay/returnUrl
    notifyUrl: http://www.fordearme.com/pay/alipay/notifyUrl


